import localFont from "next/font/local";
import "./globals.css";
import CustomNavbar from "@/components/CustomNavbar";
import Footer from "@/components/Footer";
import 'react-toastify/dist/ReactToastify.min.css';
import { ToastContainer } from "react-toastify";
// import UserContext from "@/contextAPI/userContext";
import UserProvider from "@/contextAPI/userProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <UserProvider>
          <ToastContainer/>
          {/* <div className="flex flex-col min-h-screen">
            <CustomNavbar />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div> */}
          <div className="flex flex-col min-h-screen  mx-auto">
            <CustomNavbar />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
          </div>

          
        </UserProvider>
      </body>
    </html>
  );
}
